name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq shellcheck gawk

      - name: shellcheck
        run: shellcheck $(find . -name '*.sh')

      - name: tests
        run: bash tests/test.sh

      - name: install tests
        run: bash tests/install_test.sh
